apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres
spec: 
  selector: 
    matchLabels: 
      app: postgres
  template: 
    metadata: 
      labels: 
        app: postgres
    spec: 
      containers: 
        - name: postgres
          image: postgres:16.0
          env: 
            - name: POSTGRES_PASSWORD
              value: SecretPost
            - name: POSTGRES_USER
              value: userpostgres
          ports: 
            - containerPort: 5432
          volumeMounts: 
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes: 
        - name: postgresdb
          persistentVolumeClaim: 
            claimName: postgres-pvc
            
---

apiVersion: v1
kind: Service
metadata: 
  name: postgres-service
spec: 
  selector: 
    app: postgres
  ports: 
    - port: 5432



--- 

apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: postgres-interface
spec: 
  selector: 
    matchLabels: 
      app: pgadmin4
  template: 
    metadata: 
      labels: 
        app: pgadmin4
    spec: 
      containers: 
        - name: pgadmin4
          image: dpage/pgadmin4:7.7
          ports: 
            - containerPort: 80
          env: 
            - name: PGADMIN_DEFAULT_EMAIL
              value: user@domain.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: SuperSecret

---

apiVersion: v1
kind: Service
metadata: 
  name: postgres-interface
spec: 
  selector: 
    app: pgadmin4
  ports: 
    - port: 8081
      targetPort: 80
  type: LoadBalancer